services:
  bot:
    build: .
    env_file:
      - ./env/pythonas.env
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - ./env/pythonas.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

